### ISSUE TITLE
Obs

### ISSUE THREAD

**Issue by osouza-de** [iMandin/Desafio-CloudOpss#1]
@iMandin, eu gostaria de parabenizar pela solução, em especial, o cuidado que você teve em detalhar o passo a passo.

Continue com esse zelo todo no teu trabalho pois trará como resultado o teu sucesso.

**Parabéns**.

**Comment by iMandin** [comment]
> @iMandin, eu gostaria de parabenizar pela solução, em especial, o cuidado que você teve em detalhar o passo a passo.
> 
> Continue com esse zelo todo no teu trabalho pois trará como resultado o teu sucesso.
> 
> **Parabéns**.

Hey! Obrigada, vou continuar me esforçando :)
